=encoding utf8

=head1 ABOUT

This is some Perl code that reproduces a bug in Perl. To run go over the source
files (to make sure they do not contain anything nasty) and then run
"sh driver.sh" .

=head1 LICENSE

License is multi-licensed as MIT/X11/Public Domain/CC-Zero/Artistic 2.0/Same-terms-as-Perl/License-of-your-choice.

=cut
